### ISSUE TITLE
add a version number to the backupminder plist output

### ISSUE THREAD

**Issue by YesThatAllen** [watchmanmonitoring/backupminder#12]
so that we can warn if the version is missing or too old

**Comment by garybourgeois** [comment]
Is this something we can pull from the app?  From an `Info.plist` or something?  Where do we keep the version number?

**Comment by YesThatAllen** [comment]
yes, it would be 

> /Applications/BackupMinderUI.app/Contents/Info.plist CFBundleVersion

```
	<key>CFBundleVersion</key>
	<string>1.1.0</string>
```

**Comment by YesThatAllen** [comment]
and 1.2 will be the one we release with this build

**Comment by garybourgeois** [comment]
I'm leaning more towards just having the plugin look there, and making this a client issue instead of a BackupMinder one.  That would be effective immediately, and honestly I'd probably just have BackupMinder get it from there anyways so we don't have to keep up with it in the code itself.

**Comment by YesThatAllen** [comment]
Works. Will track in the plugin itself.
