### ISSUE TITLE
Prevent a corrupt status log from stopping BackupMinder

### ISSUE THREAD

**Issue by YesThatAllen** [watchmanmonitoring/backupminder#23]
there are reported cases where a corrupt `BackupMinder_Log.plist` occurs.

In cases like this, BackupMinder should remove & restart the log file

**Comment by garybourgeois** [comment]
It already should according to this:  178da8b78d92f4584f5e5066bea9e3d396070381

Do you remember if the cases of that happening were of older versions?

**Comment by YesThatAllen** [comment]
I just happened now.. but I bet it's just the wrong version of the script 

```
eading Backup Minder log file ...
Could not read plist: /Library/Application Support/BackupMinder/BackupMinder_Log.plist

File read error:
<class 'xml.parsers.expat.ExpatError'>
junk after document element: line 3, column 3
Traceback (most recent call last):
  File "/Library/MonitoringClient/Plugins/check_backup_minder.plugin", line 62, in <module>
    bm_log = readPlist(bm_log_file)
  File "/Library/MonitoringClient/Utilities/Modules/PluginToolkit.py", line 57, in readPlist
    print('\nPlist data:\n' % plist_data)
TypeError: not all arguments converted during string formatting
bash-3.2# 
```

**Comment by garybourgeois** [comment]
That ... was a bug in the client toolkit, which may or may not be related to a BackupMinder problem (because sometimes reading a plist just breaks).

**Comment by YesThatAllen** [comment]
confirmed that the latest backupminder will destroy and recreate a corrupt log plist
