### ISSUE TITLE
autoupdate needed

### ISSUE THREAD

**Issue by YesThatAllen** [watchmanmonitoring/backupminder#8]
An auto-update mechanism will be needed.. I assume http://sparkle.andymatuschak.org/ is the right choice... http://sparkle.andymatuschak.org/

**Comment by YesThatAllen** [comment]
We're using Sparkle 1.5b6 until it's limiting the functionality of the BackupMinder app

**Comment by apple4ever** [comment]
Is this done?

**Comment by YesThatAllen** [comment]
Nope, still need this

**Comment by apple4ever** [comment]
Ok what needs done now that the update functionality is in the app?
